
// This file is autogenerated by `next-dev-server.js`.
// It contains type definitions for `process.env`.
// Next.js will automatically pick it up.
// It is recommended to add this file to your `.gitignore`.

interface ProcessEnv {
  NODE_ENV: 'development' | 'production' | 'test'
  GITHUB_REPO_OWNER: string
  GITHUB_REPO_NAME: string
  GITHUB_PAT: string
  GEMINI_API_KEY: string
}

// Extend `process.env` with the custom `ProcessEnv` interface.
declare namespace NodeJS {
  interface ProcessEnv extends ProcessEnv {}
}
